version: '3.8'

services:
  brain-analyzer:
    build: .
    container_name: brain-source-analysis
    ports:
      - "8050:8050"
    volumes:
      # Mount your data directory
      - ./music_cache:/app/music_cache
      # Mount output directories
      - ./brain_images:/app/brain_images
      - ./custom_brain_images:/app/custom_brain_images
      - ./exported_data:/app/exported_data
      # Optional: mount custom configuration
      - ./config:/app/config
    environment:
      - DISPLAY=:99
      - PYVISTA_OFF_SCREEN=true
      - MNE_3D_BACKEND=pyvista
      # Optional: customize application settings
      - BRAIN_ANALYZER_PORT=8050
      - BRAIN_ANALYZER_HOST=0.0.0.0
      - BRAIN_ANALYZER_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits (adjust based on your data size)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    
  # Optional: Add a reverse proxy for production deployment
  nginx:
    image: nginx:alpine
    container_name: brain-analyzer-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # For SSL certificates (production)
      - ./certs:/etc/nginx/certs
    depends_on:
      - brain-analyzer
    restart: unless-stopped
    profiles:
      - production

# Optional: Add a database for storing analysis results
volumes:
  brain_data:
    driver: local
  analysis_results:
    driver: local

networks:
  brain-network:
    driver: bridge 